services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.5.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:9200/_cluster/health || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 10

  rag-app:
    build: .
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - HF_TOKEN=${HF_TOKEN}
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    stdin_open: true
    tty: true

volumes:
  elasticsearch_data: